### ISSUE TITLE
Test run doesn't work on Tomcat 7.0.62

### ISSUE THREAD

**Issue by xappymah** [excelsior-oss/excelsior-jet-maven-plugin#42]
When running "testrun" task with Tomcat 7.0.62 the following error happens:

```
[ERROR] Exception in thread "main" java.lang.NoClassDefFoundError: org.apache.juli.logging.LogFactory
[ERROR]     at org.apache.catalina.startup.Bootstrap.<clinit>(Unknown Source)
[ERROR] Caused by: java.lang.ClassNotFoundException: org.apache.juli.logging.LogFactory
[ERROR]     at java.net.URLClassLoader.findClass(Unknown Source)
[ERROR]     at java.lang.ClassLoader.loadClass(Unknown Source)
[ERROR]     at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[ERROR]     at java.lang.ClassLoader.loadClass(Unknown Source)
[ERROR]     ... 1 more
```

**Comment by pjBooms** [comment]
The issues is fixed in 0.9.1 release
